# Generated by Django 3.0.8 on 2020-07-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilog_api', '0002_auto_20200718_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
